# Lesson 2: Data Manipulation with NumPy & Pandas
Prepared by Festus Ogungbemiro

## Overview
In the previous lesson, we learned the fundamentals of Python programming. Now we will explore two essential libraries for scientific computing: **NumPy** and **Pandas**. These libraries form the backbone of data manipulation in Python and are essential for handling the large datasets we will encounter in nanoinformatics. By the end of this lesson, you will be able to efficiently load, clean, transform, and analyse tabular data skills you will use extensively when working with Materials Project data in later lessons.

## Learning Objectives
After completing this lesson, you will be able to:

- Create and manipulate NumPy arrays for efficient numerical computations.
- Perform vectorised operations on arrays without explicit loops.
- Load, inspect, and clean data using Pandas Series and DataFrames.
- Filter, group, and aggregate data to extract meaningful insights.
- Merge and reshape DataFrames for analysis.
- Apply these skills to real materials science data (e.g., atomic properties, band gaps).

## Prerequisites
- Completion of Lesson 1 or equivalent Python knowledge.
- Python 3.8+ installed with Jupyter Notebook.
- Basic understanding of lists, dictionaries, and functions.

---
## 1. Introduction to NumPy

### 1.1 What is NumPy?
NumPy (Numerical Python) is the fundamental package for scientific computing in Python. It provides:
- A powerful N-dimensional array object (`ndarray`)
- Fast vectorised operations (no explicit loops needed)
- Tools for linear algebra, Fourier transforms, and random number generation
- Integration with C/C++ and Fortran code

In nanoinformatics, NumPy is used extensively for handling large arrays of numerical data, such as band gaps, formation energies, and atomic coordinates.

### 1.2 Installing NumPy
If you haven't installed NumPy yet, you can do so using pip:

In [1]:
# Uncomment the line below to install NumPy
!pip install numpy

Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (2.3.5)

### 1.3 Creating NumPy Arrays
The main object in NumPy is the homogeneous multidimensional array (`ndarray`). Let's create arrays from Python lists:

In [2]:
import numpy as np

# Create a 1D array from a list
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)
print("Type:", type(arr1))
print("Shape:", arr1.shape)
print("Data type:", arr1.dtype)

# Create a 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D array:\n", arr2)
print("Shape:", arr2.shape)  # (rows, columns)

# Create arrays with built-in functions
zeros = np.zeros((3, 4))      # 3x4 array of zeros
ones = np.ones((2, 3))        # 2x3 array of ones
identity = np.eye(3)          # 3x3 identity matrix
random_arr = np.random.rand(2, 2)  # 2x2 random numbers between 0 and 1

print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nIdentity:\n", identity)
print("\nRandom:\n", random_arr)

1D array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Shape: (5,)
Data type: int64

2D array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random:
 [[0.64634066 0.07770861]
 [0.52656186 0.8146676 ]]

**Exercise 1.1**: Create a 4×4 array of random integers between 0 and 10. *Hint: use `np.random.randint()`*.

In [3]:
# Your code here

### 1.4 Array Indexing and Slicing
NumPy arrays support indexing and slicing similar to Python lists, but with additional capabilities for multidimensional arrays.

In [4]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Original array:\n", arr)

# Indexing
print("Element at row 0, col 1:", arr[0, 1])   # 20
print("First row:", arr[0, :])                 # [10 20 30]
print("Second column:", arr[:, 1])             # [20 50 80]

# Slicing
print("Submatrix (first 2 rows, last 2 columns):\n", arr[:2, 1:3])

# Boolean indexing (select elements > 50)
print("Elements > 50:", arr[arr > 50])

Original array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at row 0, col 1: 20
First row: [10 20 30]
Second column: [20 50 80]
Submatrix (first 2 rows, last 2 columns):
 [[20 30]
 [50 60]]
Elements > 50: [60 70 80 90]

**Exercise 1.2**: From the array `arr` above, extract the submatrix consisting of the last two rows and the first two columns.

In [5]:
# Your code here

### 1.5 Vectorised Operations
One of NumPy's greatest strengths is the ability to perform element-wise operations on entire arrays without explicit loops. This is called **vectorisation** and leads to much faster code.

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Element-wise operations
print("a + b =", a + b)
print("a * b =", a * b)
print("a ** 2 =", a ** 2)
print("np.sqrt(a) =", np.sqrt(a))
print("np.sin(a) =", np.sin(a))

# Comparisons return boolean arrays
print("a > 2 =", a > 2)
print("a == 3 =", a == 3)

a + b = [11 22 33 44]
a * b = [ 10  40  90 160]
a ** 2 = [ 1  4  9 16]
np.sqrt(a) = [1.         1.41421356 1.73205081 2.        ]
np.sin(a) = [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
a > 2 = [False False  True  True]
a == 3 = [False False  True False]

**Exercise 1.3**: Create two NumPy arrays representing the atomic masses of Ag, Cu, Zn, and Ti, and the number of atoms of each element in a hypothetical alloy. Compute the total mass of the alloy.

In [7]:
# Your code here

### 1.6 Useful NumPy Functions
NumPy provides a wide range of functions for statistical and mathematical operations.

In [8]:
data = np.array([2.5, 3.1, 4.0, 2.8, 3.6])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard deviation:", np.std(data))
print("Min:", np.min(data))
print("Max:", np.max(data))
print("Sum:", np.sum(data))
print("Cumulative sum:", np.cumsum(data))

Mean: 3.1999999999999997
Median: 3.1
Standard deviation: 0.5403702434442519
Min: 2.5
Max: 4.0
Sum: 15.999999999999998
Cumulative sum: [ 2.5  5.6  9.6 12.4 16. ]

**Exercise 1.4**: Generate an array of 1000 random numbers from a normal distribution (mean=0, std=1). Compute its mean and standard deviation. They should be close to 0 and 1 respectively.

In [9]:
# Your code here

---
## 2. Introduction to Pandas

### 2.1 What is Pandas?
Pandas is a powerful library for data manipulation and analysis. It introduces two main data structures:
- **Series**: one-dimensional labeled array (like a column in a spreadsheet)
- **DataFrame**: two-dimensional labeled data structure (like a table)

Pandas is built on top of NumPy and is the tool of choice for working with tabular data in Python. In this course, we will use Pandas to handle the results of Materials Project queries, engineer features, and prepare data for machine learning.

### 2.2 Installing Pandas
If you haven't installed Pandas yet, you can do so with pip:

In [10]:
# Uncomment the line below to install Pandas
!pip install pandas

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### 2.3 Creating Series and DataFrames

In [11]:
import pandas as pd

# Creating a Series from a list
s = pd.Series([1, 3, 5, 7, 9], name="odd_numbers")
print("Series:\n", s)
print("Index:", s.index)
print("Values:", s.values)

# Creating a DataFrame from a dictionary
data = {
    "Element": ["Ag", "Cu", "Zn", "Ti"],
    "Atomic_Number": [47, 29, 30, 22],
    "Atomic_Mass": [107.87, 63.55, 65.38, 47.87],
    "Band_Gap": [0.0, 0.0, 3.3, 0.0]  # Approximate band gaps in eV
}
df = pd.DataFrame(data)
print("\nDataFrame:\n", df)

Series:
 0    1
1    3
2    5
3    7
4    9
Name: odd_numbers, dtype: int64
Index: RangeIndex(start=0, stop=5, step=1)
Values: [1 3 5 7 9]

DataFrame:
   Element  Atomic_Number  Atomic_Mass  Band_Gap
0      Ag             47       107.87       0.0
1      Cu             29        63.55       0.0
2      Zn             30        65.38       3.3
3      Ti             22        47.87       0.0

**Exercise 2.1**: Create a DataFrame with columns "Material", "Formation_Energy", and "Density" for five hypothetical materials.

In [12]:
# Your code here

### 2.4 Inspecting DataFrames
Pandas provides many convenient methods to quickly inspect your data.

In [13]:
print("First 2 rows:\n", df.head(2))
print("\nLast 2 rows:\n", df.tail(2))
print("\nDataFrame info:")
df.info()
print("\nSummary statistics:")
df.describe()

First 2 rows:
   Element  Atomic_Number  Atomic_Mass  Band_Gap
0      Ag             47       107.87       0.0
1      Cu             29        63.55       0.0

Last 2 rows:
   Element  Atomic_Number  Atomic_Mass  Band_Gap
2      Zn             30        65.38       3.3
3      Ti             22        47.87       0.0

DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Element        4 non-null      object
 1   Atomic_Number  4 non-null      int64
 2   Atomic_Mass    4 non-null      float64
 3   Band_Gap       4 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 260.0+ bytes

Summary statistics:

       Atomic_Number  Atomic_Mass  Band_Gap
count       4.000000     4.000000     4.000
mean       32.000000    71.167500     0.825
std        10.614456    25.699342     1.650
min        22.000000    47.870000     0.000
25%        27.250000    59.630000     0.000
50%        29.500000    64.465000     0.000
75%        34.250000    76.002500     0.825
max        47.000000   107.870000     3.300

### 2.5 Selecting Data
Pandas offers multiple ways to select data: by label (`.loc`), by position (`.iloc`), or by boolean conditions.

In [14]:
# Select a single column
print("Element column:\n", df["Element"])
print("\nType:", type(df["Element"]))  # Series

# Select multiple columns
print("\nTwo columns:\n", df[["Element", "Band_Gap"]])

# Select rows by label (using index)
print("\nRow with index 2:\n", df.loc[2])

# Select rows by position
print("\nFirst two rows:\n", df.iloc[0:2])

# Boolean indexing (select materials with band gap > 0)
print("\nMaterials with band gap > 0:\n", df[df["Band_Gap"] > 0])

Element column:
 0    Ag
1    Cu
2    Zn
3    Ti
Name: Element, dtype: object

Type: <class 'pandas.core.series.Series'>

Two columns:
   Element  Band_Gap
0      Ag       0.0
1      Cu       0.0
2      Zn       3.3
3      Ti       0.0

Row with index 2:
 Element             Zn
Atomic_Number       30
Atomic_Mass      65.38
Band_Gap           3.3
Name: 2, dtype: object

First two rows:
   Element  Atomic_Number  Atomic_Mass  Band_Gap
0      Ag             47       107.87       0.0
1      Cu             29        63.55       0.0

Materials with band gap > 0:
   Element  Atomic_Number  Atomic_Mass  Band_Gap
2      Zn             30        65.38       3.3

**Exercise 2.2**: From your DataFrame created in Exercise 2.1, select materials with density greater than 5 g/cm³.

In [15]:
# Your code here

### 2.6 Adding and Removing Columns

In [16]:
# Add a new column
df["Is_Metal"] = df["Band_Gap"] == 0
print("DataFrame with new column:\n", df)

# Remove a column
df.drop("Is_Metal", axis=1, inplace=True)
print("\nAfter dropping column:\n", df)

DataFrame with new column:
   Element  Atomic_Number  Atomic_Mass  Band_Gap  Is_Metal
0      Ag             47       107.87       0.0      True
1      Cu             29        63.55       0.0      True
2      Zn             30        65.38       3.3     False
3      Ti             22        47.87       0.0      True

After dropping column:
   Element  Atomic_Number  Atomic_Mass  Band_Gap
0      Ag             47       107.87       0.0
1      Cu             29        63.55       0.0
2      Zn             30        65.38       3.3
3      Ti             22        47.87       0.0

### 2.7 Handling Missing Data
Real-world datasets often have missing values. Pandas provides tools to detect and handle them.

In [17]:
# Create a DataFrame with missing values
df_missing = pd.DataFrame({
    "A": [1, 2, np.nan, 4],
    "B": [5, np.nan, 7, 8],
    "C": [9, 10, 11, 12]
})
print("Original DataFrame with missing values:\n", df_missing)

# Check for missing values
print("\nIs null?\n", df_missing.isnull())
print("\nCount of nulls per column:\n", df_missing.isnull().sum())

# Drop rows with any missing values
df_dropped = df_missing.dropna()
print("\nAfter dropping rows with any NaN:\n", df_dropped)

# Fill missing values with a constant
df_filled = df_missing.fillna(0)
print("\nAfter filling with 0:\n", df_filled)

# Fill missing values with the mean of the column
df_filled_mean = df_missing.fillna(df_missing.mean())
print("\nAfter filling with column means:\n", df_filled_mean)

Original DataFrame with missing values:
      A    B   C
0  1.0  5.0   9
1  2.0  NaN  10
2  NaN  7.0  11
3  4.0  8.0  12

Is null?
        A      B      C
0  False  False  False
1  False   True  False
2   True  False  False
3  False  False  False

Count of nulls per column:
 A    1
B    1
C    0
dtype: int64

After dropping rows with any NaN:
      A    B   C
0  1.0  5.0   9
3  4.0  8.0  12

After filling with 0:
      A    B   C
0  1.0  5.0   9
1  2.0  0.0  10
2  0.0  7.0  11
3  4.0  8.0  12

After filling with column means:
           A         B   C
0  1.000000  5.000000   9
1  2.000000  6.666667  10
2  2.333333  7.000000  11
3  4.000000  8.000000  12

**Exercise 2.3**: Create a small DataFrame with missing values and practice different strategies to handle them (drop, fill with mean, fill with forward fill).

In [18]:
# Your code here

---
## 3. Data Aggregation and Grouping

### 3.1 GroupBy Operations
The `groupby` method allows you to split data into groups based on some criteria, apply a function to each group, and combine the results.

In [35]:
# Import pandas first
import pandas as pd

# Create a larger DataFrame
data = {
    "Material": ["Ag", "Ag", "Cu", "Cu", "Zn", "Zn"],
    "Crystal_System": ["cubic", "cubic", "cubic", "cubic", "hexagonal", "hexagonal"],
    "Band_Gap": [0.0, 0.0, 0.0, 0.0, 3.3, 3.3],
    "Formation_Energy": [-0.1, -0.12, -0.15, -0.14, -0.2, -0.22]
}
df_materials = pd.DataFrame(data)
print("Materials DataFrame:\n", df_materials)

# Group by Material and compute mean of numeric columns
grouped_mean = df_materials.groupby("Material").mean(numeric_only=True)
print("\nMean by Material:\n", grouped_mean)

# Group by Crystal_System and compute multiple statistics using named aggregation
grouped_stats = df_materials.groupby("Crystal_System").agg(
    Band_Gap_Mean=('Band_Gap', 'mean'),
    Band_Gap_Std=('Band_Gap', 'std'),
    Formation_Energy_Min=('Formation_Energy', 'min'),
    Formation_Energy_Max=('Formation_Energy', 'max')
)
print("\nStatistics by Crystal System:\n", grouped_stats)

Materials DataFrame:
   Material Crystal_System  Band_Gap  Formation_Energy
0       Ag          cubic       0.0             -0.10
1       Ag          cubic       0.0             -0.12
2       Cu          cubic       0.0             -0.15
3       Cu          cubic       0.0             -0.14
4       Zn      hexagonal       3.3             -0.20
5       Zn      hexagonal       3.3             -0.22

Mean by Material:
           Band_Gap  Formation_Energy
Material
Ag             0.0            -0.110
Cu             0.0            -0.145
Zn             3.3            -0.210

Statistics by Crystal System:
                 Band_Gap_Mean  Band_Gap_Std  Formation_Energy_Min  \
Crystal_System
cubic                     0.0           0.0                 -0.15
hexagonal                 3.3           0.0                 -0.22

                Formation_Energy_Max
Crystal_System
cubic                           -0.1
hexagonal                       -0.2

**Exercise 3.1**: Using the `df_materials` DataFrame, group by both "Material" and "Crystal_System" and compute the count of each group.

In [23]:
# Your code here

### 3.2 Pivot Tables
Pivot tables are another powerful way to summarise data.

In [24]:
# Create a pivot table
pivot = pd.pivot_table(df_materials,
                       values="Formation_Energy",
                       index="Material",
                       columns="Crystal_System",
                       aggfunc=np.mean)
print("Pivot table (mean formation energy):\n", pivot)

Pivot table (mean formation energy):
 Crystal_System  cubic  hexagonal
Material
Ag             -0.110        NaN
Cu             -0.145        NaN
Zn                NaN      -0.21

C:\Users\HP\AppData\Local\Temp\ipykernel_8672\4151056109.py:2: FutureWarning: The provided callable <function mean at 0x000001D9141C2020> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pivot = pd.pivot_table(df_materials,

---
## 4. Merging and Joining DataFrames

Often you need to combine data from multiple sources. Pandas provides several functions for this: `merge()`, `join()`, and `concat()`.

In [25]:
# Create two DataFrames
df1 = pd.DataFrame({
    "Element": ["Ag", "Cu", "Zn"],
    "Atomic_Radius": [144, 128, 134]  # pm
})

df2 = pd.DataFrame({
    "Element": ["Ag", "Cu", "Zn"],
    "Electronegativity": [1.93, 1.90, 1.65]
})

# Merge on the common column 'Element'
merged = pd.merge(df1, df2, on="Element")
print("Merged DataFrame:\n", merged)

# Concatenate along rows
df3 = pd.DataFrame({
    "Element": ["Ti", "Au"],
    "Atomic_Radius": [147, 144],
    "Electronegativity": [1.54, 2.54]
})
concatenated = pd.concat([merged, df3], ignore_index=True)
print("\nConcatenated DataFrame:\n", concatenated)

Merged DataFrame:
   Element  Atomic_Radius  Electronegativity
0      Ag            144               1.93
1      Cu            128               1.90
2      Zn            134               1.65

Concatenated DataFrame:
   Element  Atomic_Radius  Electronegativity
0      Ag            144               1.93
1      Cu            128               1.90
2      Zn            134               1.65
3      Ti            147               1.54
4      Au            144               2.54

**Exercise 4.1**: Create two DataFrames: one with atomic masses and one with boiling points. Merge them on the element symbol.

In [26]:
# Your code here

---
## 5. Working with Realistic Nanoinformatics Data

Now let's apply what we've learned to a more realistic dataset. We'll create a DataFrame that mimics the structure of data we might get from the Materials Project.

In [27]:
# Simulate Materials Project data
np.random.seed(42)
n_materials = 20

materials_data = {
    "material_id": [f"mp-{i}" for i in range(1000, 1000+n_materials)],
    "formula": np.random.choice(["Ag", "Cu", "Zn", "Ti", "Au", "Mg", "Fe"], n_materials),
    "band_gap": np.random.uniform(0, 5, n_materials),
    "formation_energy_per_atom": np.random.uniform(-2, 1, n_materials),
    "density": np.random.uniform(2, 12, n_materials),
    "volume": np.random.uniform(50, 200, n_materials)
}

df_mp = pd.DataFrame(materials_data)
print("Simulated Materials Project DataFrame:")
df_mp.head(10)

Simulated Materials Project DataFrame:

,material_id,formula,band_gap,formation_energy_per_atom,density,volume
0,mp-1000,Fe,4.692764,-1.960205,5.951502,52.111973
1,mp-1001,Ti,0.003894,0.826605,11.266589,79.826361
2,mp-1002,Au,4.961058,-0.310135,9.272720,156.701293
3,mp-1003,Fe,3.087408,-0.843750,5.265408,168.526331
4,mp-1004,Zn,3.058266,-1.952101,7.704440,140.893996
5,mp-1005,Au,0.035332,-1.307319,7.208343,188.945132
6,mp-1006,Au,0.115312,-1.276924,11.611720,147.661554
7,mp-1007,Fe,2.623873,0.049791,10.445338,187.243951
8,mp-1008,Cu,1.999305,-0.170010,9.473201,177.505787
9,mp-1009,Zn,0.233328,0.499585,7.396921,117.417601

### 5.1 Basic Data Exploration

In [28]:
print("DataFrame info:")
df_mp.info()

print("\nSummary statistics:")
df_mp.describe()

print("\nUnique formulas:", df_mp["formula"].unique())
print("\nCount of each formula:")
print(df_mp["formula"].value_counts())

DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   material_id                20 non-null     object
 1   formula                    20 non-null     object
 2   band_gap                   20 non-null     float64
 3   formation_energy_per_atom  20 non-null     float64
 4   density                    20 non-null     float64
 5   volume                     20 non-null     float64
dtypes: float64(4), object(2)
memory usage: 1.1+ KB

Summary statistics:

Unique formulas: ['Fe' 'Ti' 'Au' 'Zn' 'Cu' 'Mg']

Count of each formula:
formula
Au    5
Zn    5
Fe    4
Ti    3
Cu    2
Mg    1
Name: count, dtype: int64

### 5.2 Filtering and Querying

In [29]:
# Find materials with band gap < 3.0 (potential semiconductors)
semiconductors = df_mp[df_mp["band_gap"] < 3.0]
print("Potential semiconductors (band gap < 3.0 eV):")
print(semiconductors[["formula", "band_gap"]])

# Find materials with formation energy < -1.0 (thermodynamically stable)
stable = df_mp[df_mp["formation_energy_per_atom"] < -1.0]
print("\nThermodynamically stable materials (formation energy < -1.0 eV/atom):")
print(stable[["formula", "formation_energy_per_atom"]])

Potential semiconductors (band gap < 3.0 eV):
   formula  band_gap
1       Ti  0.003894
5       Au  0.035332
6       Au  0.115312
7       Fe  2.623873
8       Cu  1.999305
9       Zn  0.233328
11      Zn  1.163857
12      Zn  0.453032
14      Ti  1.912310
16      Mg  2.333814
19      Ti  2.252496

Thermodynamically stable materials (formation energy < -1.0 eV/atom):
   formula  formation_energy_per_atom
0       Fe                  -1.960205
4       Zn                  -1.952101
5       Au                  -1.307319
6       Au                  -1.276924
10      Fe                  -1.479906
12      Zn                  -1.453292
15      Zn                  -1.376175
17      Au                  -1.906060

### 5.3 Adding Engineered Features
In later lessons, we will use `pymatgen` to extract detailed elemental properties. For now, let's add some simple features manually.

In [30]:
# Create a dictionary of atomic masses (simplified)
atomic_mass = {
    "Ag": 107.87,
    "Cu": 63.55,
    "Zn": 65.38,
    "Ti": 47.87,
    "Au": 196.97,
    "Mg": 24.31,
    "Fe": 55.85
}

# Map atomic mass to each row
df_mp["atomic_mass"] = df_mp["formula"].map(atomic_mass)

# Create a simple feature: mass_density_ratio
df_mp["mass_density_ratio"] = df_mp["atomic_mass"] / df_mp["density"]

print("DataFrame with engineered features:")
df_mp.head()

DataFrame with engineered features:

,material_id,formula,band_gap,formation_energy_per_atom,density,volume,atomic_mass,mass_density_ratio
0,mp-1000,Fe,4.692764,-1.960205,5.951502,52.111973,55.85,9.384185
1,mp-1001,Ti,0.003894,0.826605,11.266589,79.826361,47.87,4.248846
2,mp-1002,Au,4.961058,-0.310135,9.272720,156.701293,196.97,21.241880
3,mp-1003,Fe,3.087408,-0.843750,5.265408,168.526331,55.85,10.606966
4,mp-1004,Zn,3.058266,-1.952101,7.704440,140.893996,65.38,8.486016

### 5.4 Grouping and Aggregating

In [31]:
# Average properties by element
grouped = df_mp.groupby("formula").agg({
    "band_gap": ["mean", "std"],
    "formation_energy_per_atom": "mean",
    "density": "mean"
})
print("Average properties by element:")
print(grouped.round(3))

Average properties by element:
        band_gap        formation_energy_per_atom density
            mean    std                      mean    mean
formula
Au         2.501  2.313                    -0.907   7.817
Cu         2.700  0.992                     0.178   7.711
Fe         3.818  1.130                    -1.059   7.382
Mg         2.334    NaN                    -0.297   2.156
Ti         1.390  1.212                    -0.183   7.055
Zn         1.965  1.989                    -1.022   7.695

**Exercise 5.1**: Add another engineered feature: estimate the number of atoms in the unit cell using `volume` and `atomic_mass` (assume a simple relationship, e.g., `volume * density / atomic_mass`). Then find the element with the highest average number of atoms per unit cell.

In [32]:
# Your code here

---
## 6. Saving and Loading Data

Pandas makes it easy to save DataFrames to various formats and load them back.

In [33]:
# Save to CSV
df_mp.to_csv("materials_data.csv", index=False)
print("Data saved to materials_data.csv")

# Load from CSV
df_loaded = pd.read_csv("materials_data.csv")
print("\nLoaded DataFrame (first 3 rows):")
print(df_loaded.head(3))

# Save to Excel (requires openpyxl or xlwt)
# df_mp.to_excel("materials_data.xlsx", index=False)

# Save to pickle (fast, Python-specific format)
df_mp.to_pickle("materials_data.pkl")
df_loaded_pkl = pd.read_pickle("materials_data.pkl")

Data saved to materials_data.csv

Loaded DataFrame (first 3 rows):
  material_id formula  band_gap  formation_energy_per_atom    density  \
0     mp-1000      Fe  4.692764                  -1.960205   5.951502
1     mp-1001      Ti  0.003894                   0.826605  11.266589
2     mp-1002      Au  4.961058                  -0.310135   9.272720

       volume  atomic_mass  mass_density_ratio
0   52.111973        55.85            9.384185
1   79.826361        47.87            4.248846
2  156.701293       196.97           21.241880

**Exercise 6.1**: Save your DataFrame to a CSV file, then load it back and verify that the data is unchanged (e.g., by comparing the first row or using `df.equals()`).

In [34]:
# Your code here

---
## 7. Summary
In this lesson, we covered the essential data manipulation tools in Python:

- **NumPy**: creating arrays, indexing, vectorised operations, and statistical functions.
- **Pandas**: Series and DataFrames, selecting data, handling missing values, grouping, merging, and saving/loading data.
- We applied these skills to a simulated Materials Project dataset, mimicking real nanoinformatics workflows.

With these tools, you are now equipped to handle large datasets efficiently—a crucial skill for the upcoming lessons where we will query the actual Materials Project database and build machine learning models.

---
## 8. Further Resources
- [NumPy Quickstart Tutorial](https://numpy.org/doc/stable/user/quickstart.html)
- [Pandas Getting Started Guide](https://pandas.pydata.org/docs/getting_started/index.html)
- [10 Minutes to Pandas](https://pandas.pydata.org/docs/user_guide/10min.html)
- [Kaggle Pandas Course](https://www.kaggle.com/learn/pandas)

---
## 9. Self‑Assessment Questions
1. What is the main difference between a NumPy array and a Python list?
2. How do you select the third column of a DataFrame by position? By label?
3. What does the `groupby()` method do? Give an example.
4. How would you handle missing values in a dataset?
5. Write a line of code to save a DataFrame to a CSV file without the index column.